/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "RooKurieNHPdf.h"

#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <Riostream.h>
#include <TMath.h>

#include <cmath>

ClassImp(RooKurieNHPdf);

RooKurieNHPdf::RooKurieNHPdf(const char *name, const char *title,
			     RooAbsReal::Ref _en,
			     RooAbsReal::Ref _munu)
   : RooAbsPdf(name,title),
   en("en","en",this,_en),
   munu("munu","munu",this,_munu)
{
}

RooKurieNHPdf::RooKurieNHPdf(RooKurieNHPdf const &other, const char *name)
   : RooAbsPdf(other,name),
   en("en",this,other.en),
   munu("munu",this,other.munu)
{
}


double RooKurieNHPdf::evaluate() const 
{
   return RooKurieNHPdf_evaluate(en, munu); 
}

void RooKurieNHPdf::doEval(RooFit::EvalContext &ctx) const 
{ 
   std::span<const double> enSpan = ctx.at(en);
   std::span<const double> munuSpan = ctx.at(munu);

   std::size_t n = ctx.output().size();
   for (std::size_t i = 0; i < n; ++i) {
      ctx.output()[i] = RooKurieNHPdf_evaluate(enSpan.size() > 1 ? enSpan[i] : enSpan[0],
					       munuSpan.size() > 1 ? munuSpan[i] : munuSpan[0]);
   }
} 

void RooKurieNHPdf::translate(RooFit::Detail::CodeSquashContext &ctx) const
{
   ctx.addResult(this, ctx.buildCall("RooKurieNHPdf_evaluate", en, munu));
}
