/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooBDNormalHPdf_h
#define RooBDNormalHPdf_h

#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <complex>
#include "TBetaGenerator.hh"

class RooBDNormalHPdf : public RooAbsPdf {
public:
  RooBDNormalHPdf() {}
  RooBDNormalHPdf(const char *name, const char *title,        RooAbsReal& _en,
		  RooAbsReal& _munu);
  RooBDNormalHPdf(RooBDNormalHPdf const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new RooBDNormalHPdf(*this, newname); }
protected:

  RooRealProxy en ;
  RooRealProxy munu ;

  double evaluate() const override;
  void computeBatch(double* output, std::size_t size, RooFit::Detail::DataMap const&) const override;
  void translate(RooFit::Detail::CodeSquashContext &ctx) const override;

private:

  ClassDefOverride(RooBDNormalHPdf, 1) // Your description goes here...
};
inline double RooBDNormalHPdf_evaluate(double en, double munu) 
{
  return TBeta::dGammadE(true, munu, 0.0, 0.0, en);
}


#endif // RooBDNormalHPdf_h
