/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooBDInverseHPdf_h
#define RooBDInverseHPdf_h

#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <complex>
#include "TBetaGenerator.hh"

class RooBDInverseHPdf : public RooAbsPdf {
public:
  RooBDInverseHPdf() {}
  RooBDInverseHPdf(const char *name, const char *title,        RooAbsReal& _en,
		  RooAbsReal& _munu);
  RooBDInverseHPdf(RooBDInverseHPdf const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new RooBDInverseHPdf(*this, newname); }
protected:

  RooRealProxy en ;
  RooRealProxy munu ;

  double evaluate() const override;
  void doEval(RooFit::EvalContext &) const override;
  void translate(RooFit::Detail::CodeSquashContext &ctx) const override;

private:

  ClassDefOverride(RooBDInverseHPdf, 1) // Your description goes here...
};
inline double RooBDInverseHPdf_evaluate(double en, double munu) 
{
   return TBeta::dGammadE(false, munu, 0.0, 0.0, en);
}


#endif // RooBDInverseHPdf_h
