/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooBDNormalSterilePdf_h
#define RooBDNormalSterilePdf_h

#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <complex>
#include "TBetaGenerator.hh"

class RooBDNormalSterilePdf : public RooAbsPdf {
public:
  RooBDNormalSterilePdf() {}
  RooBDNormalSterilePdf(const char *name, const char *title,        RooAbsReal& _en,
		  RooAbsReal& _munu, RooAbsReal& _mN, RooAbsReal& _eta);
  RooBDNormalSterilePdf(RooBDNormalSterilePdf const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new RooBDNormalSterilePdf(*this, newname); }
protected:

  RooRealProxy en ;
  RooRealProxy munu ;
  RooRealProxy mN ;
  RooRealProxy eta ;
  
  double evaluate() const override;
  void computeBatch(double* output, std::size_t size, RooFit::Detail::DataMap const&) const override;
  void translate(RooFit::Detail::CodeSquashContext &ctx) const override;

private:

  ClassDefOverride(RooBDNormalSterilePdf, 1) // Your description goes here...
};
inline double RooBDNormalSterilePdf_evaluate(double en, double munu, double mN, double eta) 
{
   return TBeta::dGammadE(true, munu, mN, eta, en);
}


#endif // RooBDNormalSterilePdf_h
