/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef RooKurieNHPdf_h
#define RooKurieNHPdf_h

#include <RooAbsPdf.h>
#include <RooRealProxy.h>
#include <RooCategoryProxy.h>
#include <RooAbsReal.h>
#include <RooAbsCategory.h>

#include <complex>
#include "TBetaTools.hh"

class RooKurieNHPdf : public RooAbsPdf {
public:
  RooKurieNHPdf() {}
  RooKurieNHPdf(const char *name, const char *title,        RooAbsReal& _en,
		  RooAbsReal& _munu);
  RooKurieNHPdf(RooKurieNHPdf const &other, const char *name=nullptr);
  TObject* clone(const char *newname) const override { return new RooKurieNHPdf(*this, newname); }
protected:

  RooRealProxy en ;
  RooRealProxy munu ;

  double evaluate() const override;
  void computeBatch(double* output, std::size_t size, RooFit::Detail::DataMap const&) const override;
  void translate(RooFit::Detail::CodeSquashContext &ctx) const override;

private:

  ClassDefOverride(RooKurieNHPdf, 1) // Your description goes here...
};
inline double RooKurieNHPdf_evaluate(double en, double munu) 
{
  return TBTools::KurieTrsf(en, TBeta::dGammadE(true, munu, 0.0, 0.0, en));
}


#endif // RooKurieNHPdf_h
